### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by Britvic55** [andre0707/gcAE#2]
When adding a calendar from geocaching.com the coordinates are showing as East when it should be West.

for example https://coord.info/GCA1D4V

**Comment by andre0707** [comment]
Thanks for reporting this issue!
Update is in review with the AppStore team and should be available soon

**Comment by andre0707** [comment]
The update is now available

**Comment by Britvic55** [comment]
Thanks, what release is this?

I’m on 4.12 and that’s not working.

It’s not a big problem but taking me to Kent instead of Surrey.

Jon



Sent from my iPad

On 2 Nov 2022, at 13:55, Andre ***@***.***> wrote:

﻿

The update is now available

**Comment by andre0707** [comment]
4.13 is the new release which fixed it.
Maybe it takes some more time until the update is displayed for everyone

**Comment by Britvic55** [comment]
Sorry, my fault, I updated phone then added using ipad, doh

Cup of coffee on way !

Jon

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
