### ISSUE TITLE
Feature request: disable unused buttons

### ISSUE THREAD

**Issue by huberteff** [andre0707/gcAE#3]
I only use the „open in (app)“ button, and never use any of the other buttons. 
It would be nice to disable the unused buttons. 
manually disabling via switches would be fine, nothing fancy needed.

**Comment by andre0707** [comment]
Thanks for reaching out!

This should already be supported.
Please try the following:
- Open the gcAE main app
- Select "Configure Actions" at the very top
- Use the switches for each action you do not need and switch it of
- Go back to the main view (tap the upper left button which is labeled "gcAE") to save your changes
- Go to home screen (do not force quit the app yet)
- Switch to Safari
- Open any geocaching.com listing (if there is still one open, please reload the website)

Then you should only have the buttons you configured

**Comment by huberteff** [comment]
yes that worked, thanks a lot!

 - Hubert

**Comment by andre0707** [comment]
Thanks for letting me know it worked.
I will close this issue here then.

happy caching
